// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using MSDNFinder.Model.DataJson;
using SQLite.Net.Attributes;

namespace MSDNFinder.Model.DataJson
{

    public class ExtendedAttributes
    {
        public static readonly string TableName = "ExtendedAttributes";
        public static readonly string CreateSql = "CREATE TABLE ExtendedAttributes (_id INTEGER PRIMARY KEY NOT NULL,data_tochassubtree TEXT,data_mtpsaliasid TEXT,data_mtpsassetid TEXT,data_mtpsshortid TEXT)";

        [PrimaryKey]
        [NotNull]
        [JsonProperty("id")]
        public int _id { get; set; }

        [JsonProperty("data-tochassubtree")]
        public string data_tochassubtree { get; set; }
        [JsonProperty("data-mtpsaliasid")]
        public string data_mtpsaliasid { get; set; }
        [JsonProperty("data-mtpsassetid")]
        public string data_mtpsassetid { get; set; }
        [JsonProperty("data-mtpsshortid")]
        public string data_mtpsshortid { get; set; }
    }

}
