// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using MSDNFinder.Model.DataJson;
using SQLite.Net.Attributes;

namespace MSDNFinder.Model.DataJson
{

    [Table("ServerModel")]
    public class ServerModel
    {
        public static readonly string TableName = "servermodel";
        public static readonly string CreateSql = "CREATE TABLE ServerModel (_id INTEGER PRIMARY KEY NOT NULL,Title TEXT,Href TEXT,ToolTip TEXT,hassubtree BOOLEAN, subtreesaved BOOLEAN, parentid INTEGER, level INTEGER, skepdownload BOOLEAN )";

        [PrimaryKey]
        [AutoIncrement]
        [NotNull]
        public int _id { get; set; }

        public string Title { get; set; }
        public string Href { get; set; }
        public string ToolTip { get; set; }
        [Ignore]
        public ExtendedAttributes ExtendedAttributes { get; set; }

        public bool hassubtree { get; set; }
        public bool subtreesaved { get; set; }
        public int parentid { get; set; }
        public int level { get; set; }

        public bool skepdownload { get; set; }

        public override string ToString()
        {
            return this.Title;
        }
    }


    [Table("base_acvt")]
    public class BASE_ACVT
    {
        public static readonly string TableName = "base_acvt";
        public static readonly string CreateSql = "CREATE TABLE base_acvt (_id INTEGER PRIMARY KEY NOT NULL,acvtName TEXT,acvtObj TEXT,typ TEXT,s TEXT, seq INTEGER, isblock TEXT, originalAcvtId TEXT, isReq TEXT, ispreview TEXT, ftext TEXT, acvtCode TEXT, organization TEXT, publisher TEXT)";

        [PrimaryKey]
        [AutoIncrement]
        [NotNull]
        public int _id { get; set; }

        public string acvtName { get; set; }
        public string acvtObj { get; set; }
        public string typ { get; set; }
        public string s { get; set; }
        public int seq { get; set; }
        public string isblock { get; set; }
        public string originalAcvtId { get; set; }
        public string isReq { get; set; }
        public string ispreview { get; set; }
        public string ftext { get; set; }
        public string acvtCode { get; set; }
        public string organization { get; set; }
        public string publisher { get; set; }

        //Else Json Fields
        [Ignore]
        public int empId { get; set; }
        [Ignore]
        public int acvtId { get; set; }
        //public int originalAcvtId { get; set; }
        [Ignore]
        public object SORT { get; set; }
    }
}
